# Generated by Django 3.1.6 on 2021-03-02 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Japanese', 'Japanese'), ('French', 'French'), ('Spanish', 'Spanish'), ('German', 'German'), ('Chinese', 'Chinese'), ('Korean', 'Korean')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Booster Box', 'Booster Box'), ('Elite Trainer Box Plus', 'Elite Trainer Box Plus'), ('Elite Trainer Box', 'Elite Trainer Box'), ('Premium Collection Box', 'Premium Collection Box'), ('Pokemon Themed Box', 'Pokemon Themed Box'), ('Pin Box', 'Pin Box'), ('Theme Deck', 'Theme Deck'), ('Build and Battle Deck', 'Build and Battle Deck'), ('Premium Blister', 'Premium Blister'), ('Three Pack Blister', 'Three Pack Blister'), ('Single Pack Blister', 'Single Pack Blister'), ('Booster Pack', 'Booster Pack'), ('Single Card', 'Single Card')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='rarity',
            field=models.CharField(blank=True, choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Ultra Rare', 'Ultra Rare'), ('Amazing Rare', 'Amazing Rare'), ('Secret Rare', 'Secret Rare')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='condition',
            field=models.CharField(choices=[('Sealed Product', 'Sealed Product'), ('Pack Fresh', 'Pack Fresh'), ('Light Play', 'Light Play'), ('Moderate Play', 'Moderate Play'), ('Heavy Play', 'Heavy Play'), ('Damaged', 'Damaged')], max_length=255),
        ),
    ]
