# Generated by Django 3.1.6 on 2021-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210304_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
