# Generated by Django 3.1.6 on 2021-03-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productitem_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='stock',
        ),
    ]
