# Generated by Django 3.1.7 on 2021-03-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('booster-box', 'Booster Box'), ('elite-trainer-box-plus', 'Elite Trainer Box Plus'), ('elite-trainer-box', 'Elite Trainer Box'), ('premium-collection-box', 'Premium Collection Box'), ('pokemon-themed-box', 'Pokemon Themed Box'), ('pin-box', 'Pin Box'), ('theme-deck', 'Theme Deck'), ('build-and-battle-deck', 'Build and Battle Deck'), ('premium-blister', 'Premium Blister'), ('three-pack-blister', 'Three Pack Blister'), ('single-pack-blister', 'Single Pack Blister'), ('booster-pack', 'Booster Pack'), ('single-card', 'Single Card')], default='booster-box', max_length=255),
        ),
    ]
